/* ======================================================== */
/* EDUCATION DEVX - INSPIRATIONAL QUOTES DATABASE (200)     */
/* ======================================================== */

document.addEventListener("DOMContentLoaded", function() {
    
    const edevxQuotes = [
        // --- CHỦ ĐỀ 1: HỌC TẬP & TRI THỨC (50 Câu) ---
        { text: "Giáo dục không phải là việc đổ đầy một cái bình, mà là thắp sáng một ngọn lửa.", author: "William Butler Yeats" },
        { text: "Đầu tư vào tri thức luôn mang lại lợi nhuận cao nhất.", author: "Benjamin Franklin" },
        { text: "Học tập không phải là sự chuẩn bị cho cuộc sống, học tập chính là cuộc sống.", author: "John Dewey" },
        { text: "Bất cứ ai dừng học tập đều già đi, dù ở tuổi 20 hay 80. Bất cứ ai tiếp tục học tập đều trẻ mãi.", author: "Henry Ford" },
        { text: "Trí tuệ của con người trưởng thành trong tĩnh lặng, còn tính cách trưởng thành trong bão táp.", author: "J.W. von Goethe" },
        { text: "Học, học nữa, học mãi.", author: "V.I. Lenin" },
        { text: "Không có tài sản nào quý giá bằng sự thông minh, không có vinh quang nào lớn hơn học vấn.", author: "Socrates" },
        { text: "Một đứa trẻ, một người thầy, một cuốn sách và một cây bút có thể thay đổi thế giới.", author: "Malala Yousafzai" },
        { text: "Sự ngu dốt lớn nhất của con người là tự nhận mình đã biết tất cả.", author: "Khuyết danh" },
        { text: "Rễ của học tập thì đắng cay, nhưng quả của nó thì ngọt ngào.", author: "Aristotle" },
        { text: "Sách là phép thuật độc đáo nhất mà con người có thể mang theo bên mình.", author: "Stephen King" },
        { text: "Chúng ta học được từ thất bại nhiều hơn là từ thành công.", author: "Edgar Allan Poe" },
        { text: "Người hỏi có thể là kẻ ngốc trong 5 phút. Người không hỏi sẽ là kẻ ngốc cả đời.", author: "Ngạn ngữ Trung Quốc" },
        { text: "Học vấn do người siêng năng đạt được, tài sản do người tinh tế sở hữu, quyền lợi do người dũng cảm nắm giữ.", author: "Khuyết danh" },
        { text: "Bộ não không phải là một chiếc cốc để đổ đầy, nó là một cơ bắp cần được rèn luyện.", author: "Jim Kwik" },
        { text: "Nếu bạn nghĩ giáo dục là đắt đỏ, hãy thử tính cái giá của sự ngu dốt.", author: "Derek Bok" },
        { text: "Cách duy nhất để học Toán là làm Toán.", author: "Paul Halmos" },
        { text: "Bạn không cần phải xuất sắc để bắt đầu, nhưng bạn phải bắt đầu để trở nên xuất sắc.", author: "Zig Ziglar" },
        { text: "Mỗi ngày học thêm một điều mới là một ngày bạn không sống hoài phí.", author: "Khuyết danh" },
        { text: "Mục đích của giáo dục là thay thế một tâm trí trống rỗng bằng một tâm trí cởi mở.", author: "Malcolm Forbes" },
        { text: "Tôi không bao giờ học được gì từ những người đồng ý với tôi.", author: "Robert A. Heinlein" },
        { text: "Thế giới là một cuốn sách, và ai không đi thì chỉ đọc được một trang.", author: "St. Augustine" },
        { text: "Đừng vội tin vào những gì bạn đọc, hãy tự mình kiểm chứng bằng tư duy.", author: "Education DevX" },
        { text: "Có công mài sắt, có ngày nên kim.", author: "Tục ngữ Việt Nam" },
        { text: "Tri thức là sức mạnh.", author: "Francis Bacon" },
        { text: "Không có câu hỏi nào ngớ ngẩn, chỉ có sự im lặng là đánh mất cơ hội.", author: "Carl Sagan" },
        { text: "Năng lực tự học là kỹ năng sinh tồn quan trọng nhất của thế kỷ 21.", author: "Alvin Toffler" },
        { text: "Người đọc sách sống hàng ngàn cuộc đời trước khi chết. Người không bao giờ đọc chỉ sống một lần.", author: "George R.R. Martin" },
        { text: "Giáo dục là vũ khí mạnh nhất mà bạn có thể sử dụng để thay đổi thế giới.", author: "Nelson Mandela" },
        { text: "Học từ ngày hôm qua, sống cho ngày hôm nay, hy vọng cho ngày mai.", author: "Albert Einstein" },
        { text: "Nơi nào có ý chí, nơi đó có con đường.", author: "Pauline Kael" },
        { text: "Nếu không chịu học hỏi, bạn sẽ bị bỏ lại phía sau. Đó là quy luật của vũ trụ.", author: "Education DevX" },
        { text: "Khám phá lớn nhất của mọi thời đại là con người có thể thay đổi tương lai của mình bằng cách thay đổi thái độ.", author: "Oprah Winfrey" },
        { text: "Đi một ngày đàng, học một sàng khôn.", author: "Tục ngữ Việt Nam" },
        { text: "Sự tò mò là động cơ vĩ đại nhất của sự hiểu biết.", author: "Ken Robinson" },
        { text: "Đọc sách không cần nhiều, quan trọng là đọc đến đâu thấm đến đó.", author: "Khuyết danh" },
        { text: "Thành công trong học tập không đến từ thông minh, mà đến từ sự kiên trì nhẫn nại.", author: "Angela Duckworth" },
        { text: "Hãy trở thành sinh viên của cuộc đời, không chỉ là sinh viên của nhà trường.", author: "Education DevX" },
        { text: "Ngòi bút mạnh hơn thanh kiếm.", author: "Edward Bulwer-Lytton" },
        { text: "Trí tuệ không phải là một sản phẩm của việc học, mà là kết quả của nỗ lực cả đời để có được nó.", author: "Albert Einstein" },
        { text: "Làm việc thông minh quan trọng hơn làm việc chăm chỉ, nhưng học tập là nền tảng của cả hai.", author: "Khuyết danh" },
        { text: "Ai cũng là thiên tài. Nhưng nếu bạn đánh giá một con cá qua khả năng trèo cây, nó sẽ sống cả đời và nghĩ rằng mình ngu ngốc.", author: "Albert Einstein" },
        { text: "Nếu bạn không xây dựng ước mơ của mình, người khác sẽ thuê bạn để xây dựng ước mơ của họ.", author: "Tony Gaskins" },
        { text: "Học tập giống như chèo thuyền ngược nước, không tiến ắt sẽ lùi.", author: "Tục ngữ Trung Quốc" },
        { text: "Để có thể dạy người khác, trước hết bạn phải là một người học vĩ đại.", author: "John Wooden" },
        { text: "Giáo dục là những gì còn lại sau khi bạn đã quên những gì được học ở trường.", author: "Albert Einstein" },
        { text: "Bạn càng đọc nhiều, bạn càng biết nhiều. Bạn càng học nhiều, bạn càng đi nhiều nơi.", author: "Dr. Seuss" },
        { text: "Học tập là kho báu đi theo chủ nhân của nó tới mọi nơi.", author: "Tục ngữ Trung Quốc" },
        { text: "Khởi đầu của trí tuệ là sự nhận thức về sự ngu dốt của chính mình.", author: "Socrates" },
        { text: "Chìa khóa của sự tiến bộ là một bộ não luôn khao khát kiến thức mới.", author: "Education DevX" },

        // --- CHỦ ĐỀ 2: TƯ DUY PHÁT TRIỂN (GROWTH MINDSET - 50 Câu) ---
        { text: "Đừng sợ làm sai! Làm sai chứng tỏ bộ não của bạn đang tạo ra các nếp nhăn liên kết mới.", author: "Growth Mindset" },
        { text: "Chưa làm được không có nghĩa là không làm được. Bạn chỉ là 'Chưa' làm được thôi.", author: "Carol Dweck" },
        { text: "Thiên tài 1% là cảm hứng và 99% là mồ hôi.", author: "Thomas Edison" },
        { text: "Đừng đánh giá bản thân bằng thành công của người khác. Hãy so sánh mình với ngày hôm qua.", author: "Jordan Peterson" },
        { text: "Một sai lầm không phải là thất bại. Đó là dữ liệu giúp bạn tinh chỉnh giải pháp tiếp theo.", author: "Education DevX" },
        { text: "Bộ não con người có thể phát triển ở mọi lứa tuổi nếu nó liên tục được đối mặt với thử thách.", author: "Neuroscience" },
        { text: "Tôi không bao giờ thua. Tôi chỉ thắng hoặc học được bài học.", author: "Nelson Mandela" },
        { text: "Thất bại lớn nhất là không bao giờ dám thử.", author: "Khuyết danh" },
        { text: "Điều khó khăn nhất thường là điều mang lại sự trưởng thành lớn nhất.", author: "Education DevX" },
        { text: "Mọi chuyên gia đều từng là một người mới bắt đầu.", author: "Helen Hayes" },
        { text: "Không có giới hạn nào cho trí tuệ con người, ngoại trừ những giới hạn do chính chúng ta đặt ra.", author: "Khuyết danh" },
        { text: "Đừng nói 'Tôi không giỏi môn này'. Hãy nói 'Tôi cần thêm thời gian để luyện tập môn này'.", author: "Growth Mindset" },
        { text: "Thử thách là cơ hội để chứng minh khả năng thực sự của bạn.", author: "Khuyết danh" },
        { text: "Bạn không thể thay đổi hướng gió, nhưng bạn có thể điều chỉnh cánh buồm.", author: "Jimmy Dean" },
        { text: "Trí thông minh không cố định. Nó được bồi đắp thông qua sự rèn luyện.", author: "Carol Dweck" },
        { text: "Người có tư duy phát triển nhìn thấy cơ hội trong mọi khó khăn.", author: "Winston Churchill" },
        { text: "Đừng cầu mong cuộc sống dễ dàng hơn, hãy cầu mong bản thân mạnh mẽ hơn.", author: "Jim Rohn" },
        { text: "Chỉ khi vượt qua vùng an toàn, chúng ta mới thực sự học được điều mới.", author: "Education DevX" },
        { text: "Cách duy nhất để phát triển là dám làm những việc mà bạn chưa từng làm.", author: "Ralph Waldo Emerson" },
        { text: "Đừng sợ sự chậm chạp, hãy sợ việc đứng im.", author: "Khuyết danh" },
        { text: "Người giỏi nhất không phải là người thông minh nhất, mà là người không bao giờ bỏ cuộc.", author: "Education DevX" },
        { text: "Không có gì là không thể với một người luôn biết cố gắng.", author: "Alexander Đại đế" },
        { text: "Khi bạn muốn từ bỏ, hãy nhớ lại lý do bạn bắt đầu.", author: "Khuyết danh" },
        { text: "Hôm nay làm những việc người khác không làm, ngày mai bạn sẽ có những thứ người khác không có.", author: "Khuyết danh" },
        { text: "Nếu bạn không thử, đáp án luôn luôn là Không.", author: "Nora Roberts" },
        { text: "Thành công không phải là đích đến, thất bại không phải là vực sâu. Lòng can đảm bước tiếp mới là tất cả.", author: "Winston Churchill" },
        { text: "Đừng để những rào cản cản bước bạn. Hãy dùng nó làm bàn đạp để bật cao hơn.", author: "Education DevX" },
        { text: "Không ai có thể quay lại và bắt đầu một khởi đầu mới, nhưng bất cứ ai cũng có thể bắt đầu hôm nay và tạo ra một kết thúc mới.", author: "Maria Robinson" },
        { text: "Đừng chờ đợi cơ hội, hãy tự tạo ra nó.", author: "George Bernard Shaw" },
        { text: "Đừng giới hạn thách thức của mình. Hãy thách thức giới hạn của mình.", author: "Khuyết danh" },
        { text: "Khả năng của bạn được quyết định bởi nỗ lực của bạn.", author: "Growth Mindset" },
        { text: "Tài năng có thể mở ra cánh cửa, nhưng sự nỗ lực mới giúp bạn đi đến cuối con đường.", author: "Khuyết danh" },
        { text: "Một tư duy mở là vũ khí sắc bén nhất của người làm khoa học.", author: "Education DevX" },
        { text: "Không có đỉnh cao nào mà con người không thể vươn tới nếu đủ kiên trì.", author: "Khuyết danh" },
        { text: "Người thành công luôn tìm cách giải quyết vấn đề. Kẻ thất bại luôn tìm lý do đổ lỗi.", author: "Khuyết danh" },
        { text: "Điều khác biệt giữa người thành công và người bình thường không phải là sức mạnh hay kiến thức, mà là ý chí.", author: "Vince Lombardi" },
        { text: "Nếu bạn nghĩ bạn có thể hay không thể, bạn đều đúng.", author: "Henry Ford" },
        { text: "Trở ngại là những thứ đáng sợ bạn nhìn thấy khi rời mắt khỏi mục tiêu của mình.", author: "Henry Ford" },
        { text: "Khi một cánh cửa đóng lại, một cánh cửa khác sẽ mở ra.", author: "Alexander Graham Bell" },
        { text: "Hãy làm những việc nhỏ với một tình yêu vĩ đại.", author: "Mẹ Teresa" },
        { text: "Tương lai thuộc về những ai tin vào vẻ đẹp trong những giấc mơ của họ.", author: "Eleanor Roosevelt" },
        { text: "Đừng để những gì bạn không thể làm cản trở những gì bạn có thể làm.", author: "John Wooden" },
        { text: "Kỷ luật là chiếc cầu nối giữa mục tiêu và thành tựu.", author: "Jim Rohn" },
        { text: "Đam mê là khởi đầu, nhưng sự kiên định mới tạo nên kiệt tác.", author: "Education DevX" },
        { text: "Không có con đường tắt dẫn đến bất kỳ nơi nào đáng giá.", author: "Beverly Sills" },
        { text: "Một hành trình ngàn dặm luôn bắt đầu bằng một bước đi nhỏ bé.", author: "Lão Tử" },
        { text: "Bạn không thể xây dựng danh tiếng trên những gì bạn dự định làm.", author: "Henry Ford" },
        { text: "Mọi khó khăn đều là một món quà ẩn giấu.", author: "Khuyết danh" },
        { text: "Bí mật của việc tiến lên phía trước là bắt đầu.", author: "Mark Twain" },
        { text: "Sức mạnh không đến từ những gì bạn có thể làm. Nó đến từ việc vượt qua những gì bạn từng nghĩ mình không thể.", author: "Rikki Rogers" },

        // --- CHỦ ĐỀ 3: KỶ LUẬT & HÀNH ĐỘNG (50 Câu) ---
        { text: "Cách duy nhất để hoàn thành một công việc vĩ đại là yêu những gì bạn làm.", author: "Steve Jobs" },
        { text: "Nếu bạn muốn đạt được những điều vĩ đại, hãy dừng việc xin phép.", author: "Khuyết danh" },
        { text: "Sự chần chừ là kẻ cắp của thời gian.", author: "Edward Young" },
        { text: "Kỷ luật là chọn giữa những gì bạn muốn bây giờ và những gì bạn muốn nhất.", author: "Abraham Lincoln" },
        { text: "Động lực giúp bạn bắt đầu. Thói quen giúp bạn bước tiếp.", author: "Jim Ryun" },
        { text: "Những người thành công có thói quen làm những việc mà những người thất bại không thích làm.", author: "Thomas Edison" },
        { text: "Đừng chờ đợi hoàn hảo. Hãy bắt đầu và làm cho nó hoàn hảo.", author: "Education DevX" },
        { text: "Hôm nay tôi sẽ làm những gì người khác không làm, để ngày mai tôi có thể làm những gì người khác không thể.", author: "Jerry Rice" },
        { text: "Ý tưởng không có giá trị nếu không được thực thi.", author: "Thomas Edison" },
        { text: "Cách tốt nhất để dự đoán tương lai là tạo ra nó.", author: "Peter Drucker" },
        { text: "Bí mật của thành công là làm những điều bình thường theo một cách phi thường.", author: "John D. Rockefeller" },
        { text: "Không có bí quyết nào cả. Hãy tập trung, nỗ lực và không bao giờ bỏ cuộc.", author: "Education DevX" },
        { text: "Hãy làm việc trong im lặng, để thành công của bạn lên tiếng.", author: "Khuyết danh" },
        { text: "Kỷ luật tự giác là trung tâm của mọi thành công vật chất.", author: "Brian Tracy" },
        { text: "Một giờ thực hành có giá trị hơn cả chục bài lý thuyết suông.", author: "Khuyết danh" },
        { text: "Nếu bạn không kiểm soát thời gian của mình, người khác sẽ làm điều đó.", author: "Khuyết danh" },
        { text: "Bạn không thể có một ngày mai tốt đẹp hơn nếu bạn vẫn cứ nghĩ về ngày hôm qua.", author: "Charles Kettering" },
        { text: "Hãy là phiên bản tốt nhất của chính bạn, đừng là bản sao của người khác.", author: "Judy Garland" },
        { text: "Người tập trung vào một mục tiêu duy nhất luôn nhanh hơn kẻ làm mười việc cùng lúc.", author: "Education DevX" },
        { text: "Sự tập trung là nghệ thuật nói Không với hàng ngàn thứ khác.", author: "Steve Jobs" },
        { text: "Không bao giờ là quá muộn để trở thành người mà bạn muốn trở thành.", author: "George Eliot" },
        { text: "Cách để bắt đầu là ngừng nói và bắt tay vào làm.", author: "Walt Disney" },
        { text: "Bạn có thể có kết quả hoặc có lý do. Không thể có cả hai.", author: "Arnold Schwarzenegger" },
        { text: "Cái giá của kỷ luật luôn rẻ hơn cái giá của sự hối hận.", author: "Jim Rohn" },
        { text: "Người khổng lồ cũng được tạo ra từ những bước đi nhỏ nhất mỗi ngày.", author: "Education DevX" },
        { text: "Một quyết định nhỏ hôm nay có thể thay đổi toàn bộ quỹ đạo cuộc đời bạn.", author: "Khuyết danh" },
        { text: "Thành công được xây dựng bằng cách làm những việc đơn giản một cách xuất sắc mỗi ngày.", author: "Khuyết danh" },
        { text: "Không phải chúng ta có ít thời gian, mà là chúng ta lãng phí quá nhiều thời gian.", author: "Seneca" },
        { text: "Đừng đếm những ngày trôi qua. Hãy làm cho mỗi ngày trôi qua đều đáng giá.", author: "Muhammad Ali" },
        { text: "Đổ lỗi cho hoàn cảnh là cách nhanh nhất để đánh mất quyền kiểm soát cuộc đời.", author: "Education DevX" },
        { text: "Mọi thứ đều khó khăn trước khi chúng trở nên dễ dàng.", author: "Thomas Fuller" },
        { text: "Hãy sống như thể bạn sẽ chết ngày mai. Hãy học như thể bạn sẽ sống mãi mãi.", author: "Mahatma Gandhi" },
        { text: "Khác biệt giữa một người thành công và những người khác không phải là sức mạnh hay kiến thức, mà là ý chí.", author: "Vince Lombardi" },
        { text: "Người ta không lười biếng. Họ chỉ có những mục tiêu không truyền cảm hứng cho họ.", author: "Tony Robbins" },
        { text: "Hãy tập trung vào quá trình, không phải kết quả. Quá trình tốt sẽ mang lại kết quả tốt.", author: "Education DevX" },
        { text: "Bất kể bạn cảm thấy thế nào, hãy thức dậy, mặc đồ, và xuất hiện.", author: "Khuyết danh" },
        { text: "Sự chuẩn bị tốt nhất cho ngày mai là làm tốt nhất công việc của ngày hôm nay.", author: "H. Jackson Brown Jr." },
        { text: "Khi bạn thay đổi góc nhìn, những thứ bạn nhìn sẽ thay đổi.", author: "Wayne Dyer" },
        { text: "Không có áp lực, không có kim cương.", author: "Thomas Carlyle" },
        { text: "Mọi thành tựu vĩ đại đều bắt đầu từ một quyết định dũng cảm: Bắt đầu.", author: "Khuyết danh" },
        { text: "Nếu bạn thấy mệt mỏi, hãy học cách nghỉ ngơi, đừng học cách bỏ cuộc.", author: "Banksy" },
        { text: "Sự kiên nhẫn và kiên trì có tác dụng phép thuật, khiến mọi khó khăn biến mất và rào cản tan biến.", author: "John Quincy Adams" },
        { text: "Những rào cản lớn nhất đôi khi chỉ nằm trong suy nghĩ của bạn.", author: "Education DevX" },
        { text: "Thành công không phải là chìa khóa của hạnh phúc. Hạnh phúc là chìa khóa của thành công.", author: "Albert Schweitzer" },
        { text: "Sự thay đổi không bao giờ là đau đớn. Chỉ có sự kháng cự lại thay đổi mới đau đớn.", author: "Buddha" },
        { text: "Đừng hạ thấp mục tiêu của bạn xuống ngang bằng với khả năng hiện tại. Hãy nâng cao khả năng để đạt được mục tiêu.", author: "Khuyết danh" },
        { text: "Tập trung là năng lực siêu phàm nhất trong thời đại phân tâm này.", author: "Cal Newport" },
        { text: "Mỗi một việc bạn hoàn thành đều xây dựng sự tự tin cho việc tiếp theo.", author: "Education DevX" },
        { text: "Mọi cuộc hành trình vĩ đại đều bắt đầu từ một người dám mơ mộng.", author: "Khuyết danh" },
        { text: "Chất lượng cuộc sống của bạn được quyết định bởi chất lượng thói quen của bạn.", author: "James Clear" },

        // --- CHỦ ĐỀ 4: TRIẾT LÝ CUỘC SỐNG & SỰ NGHIỆP (50 Câu) ---
        { text: "Hạnh phúc không phải là có những gì bạn muốn, mà là muốn những gì bạn có.", author: "Dale Carnegie" },
        { text: "Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó.", author: "Charles R. Swindoll" },
        { text: "Thời gian là thứ tài sản duy nhất mà tất cả mọi người đều có số lượng bằng nhau.", author: "Education DevX" },
        { text: "Người khôn ngoan học từ sai lầm của người khác. Kẻ ngốc học từ sai lầm của chính mình.", author: "Otto von Bismarck" },
        { text: "Không có con đường dẫn đến hạnh phúc. Hạnh phúc chính là con đường.", author: "Thích Nhất Hạnh" },
        { text: "Đôi khi bạn phải buông bỏ những thứ tốt để nhường chỗ cho những thứ vĩ đại.", author: "John D. Rockefeller" },
        { text: "Thái độ của bạn, không phải năng lực của bạn, sẽ quyết định độ cao của bạn.", author: "Zig Ziglar" },
        { text: "Sự giàu có thực sự của một người là những kiến thức mà họ mang theo trong tâm trí.", author: "Education DevX" },
        { text: "Bạn không cần phải kiểm soát suy nghĩ của mình. Bạn chỉ cần ngừng để chúng kiểm soát bạn.", author: "Dan Millman" },
        { text: "Lòng biết ơn là cánh cửa mở ra sự dư dả trong cuộc sống.", author: "Deepak Chopra" },
        { text: "Tài sản lớn nhất bạn có thể tích lũy là năng lực thích nghi với mọi sự thay đổi.", author: "Education DevX" },
        { text: "Hãy là sự thay đổi mà bạn muốn thấy trên thế giới này.", author: "Mahatma Gandhi" },
        { text: "Mọi vĩ nhân đều có một khởi đầu khiêm tốn.", author: "Khuyết danh" },
        { text: "Giàu có không nằm ở lượng tài sản bạn có, mà nằm ở mức độ tự do bạn nắm giữ.", author: "Naval Ravikant" },
        { text: "Đừng đánh giá một người qua câu trả lời của họ, hãy đánh giá qua câu hỏi của họ.", author: "Voltaire" },
        { text: "Sự vĩ đại không đến từ việc làm những điều phi thường, mà làm những điều bình thường với tình yêu phi thường.", author: "Mẹ Teresa" },
        { text: "Tiền bạc chỉ là công cụ. Nó sẽ đưa bạn đến bất cứ đâu bạn muốn, nhưng sẽ không thể thay thế bạn cầm lái.", author: "Ayn Rand" },
        { text: "Người duy nhất bạn nên cố gắng để giỏi hơn, chính là bạn của ngày hôm qua.", author: "Khuyết danh" },
        { text: "Nỗi sợ hãi giết chết nhiều ước mơ hơn là sự thất bại.", author: "Suzy Kassem" },
        { text: "Lạc quan là niềm tin dẫn đến thành tựu. Không có gì có thể được hoàn thành nếu không có hy vọng.", author: "Helen Keller" },
        { text: "Đừng bao giờ để sự ồn ào từ ý kiến của người khác lấn át tiếng nói bên trong bạn.", author: "Steve Jobs" },
        { text: "Giá trị thực sự của một con người không nằm ở việc anh ta vượt qua người khác như thế nào, mà là anh ta vượt qua chính mình ra sao.", author: "Education DevX" },
        { text: "Sự đơn giản là đỉnh cao của sự tinh tế.", author: "Leonardo da Vinci" },
        { text: "Một cái đầu đầy nỗi sợ hãi sẽ không có chỗ cho những ước mơ.", author: "Khuyết danh" },
        { text: "Đừng sợ đối mặt với cái bóng của mình, vì điều đó có nghĩa là có ánh sáng ở gần đó.", author: "Khuyết danh" },
        { text: "Hãy sống như một bông hoa hướng dương, luôn hướng về phía ánh sáng.", author: "Khuyết danh" },
        { text: "Sức mạnh thực sự không nằm ở việc không bao giờ ngã, mà nằm ở việc luôn đứng dậy sau mỗi lần vấp ngã.", author: "Nelson Mandela" },
        { text: "Nếu bạn muốn đi nhanh, hãy đi một mình. Nếu bạn muốn đi xa, hãy đi cùng nhau.", author: "Tục ngữ Châu Phi" },
        { text: "Những tâm trí lớn bàn luận về ý tưởng; những tâm trí trung bình bàn luận về sự kiện; những tâm trí nhỏ bé bàn luận về người khác.", author: "Eleanor Roosevelt" },
        { text: "Cách tốt nhất để tìm lại chính mình là đánh mất mình trong sự phục vụ người khác.", author: "Mahatma Gandhi" },
        { text: "Đừng khóc vì nó đã kết thúc, hãy mỉm cười vì nó đã xảy ra.", author: "Dr. Seuss" },
        { text: "Cảm ơn những người đã nói KHÔNG với tôi. Nhờ họ mà tôi đã tự mình làm lấy.", author: "Albert Einstein" },
        { text: "Hãy chọn một công việc mà bạn yêu thích, và bạn sẽ không bao giờ phải làm việc một ngày nào trong đời.", author: "Khổng Tử" },
        { text: "Thế giới chia làm hai loại người: những người nói 'tôi có thể' và những người nói 'tôi không thể'. Cả hai đều đúng.", author: "Henry Ford" },
        { text: "Đừng sống cùng một năm đến 75 lần và gọi đó là một cuộc đời.", author: "Robin Sharma" },
        { text: "Một nụ cười có thể mở ra những cánh cửa khóa chặt nhất.", author: "Khuyết danh" },
        { text: "Sự khác biệt giữa vĩ đại và bình thường thường nằm ở sự chú ý đến chi tiết.", author: "Education DevX" },
        { text: "Người hạnh phúc nhất không phải là người có những thứ tốt nhất, mà là người biết tận hưởng những thứ họ có.", author: "Khuyết danh" },
        { text: "Cuộc sống không phải là chờ đợi cơn bão đi qua, mà là học cách khiêu vũ trong cơn mưa.", author: "Vivian Greene" },
        { text: "Bạn không thể quay ngược thời gian, nhưng bạn có thể bắt đầu lại từ hôm nay.", author: "Khuyết danh" },
        { text: "Những người điên rồ nghĩ rằng họ có thể thay đổi thế giới, thường là những người làm được điều đó.", author: "Steve Jobs" },
        { text: "Đừng bao giờ hối tiếc về một ngày trong cuộc đời bạn. Ngày tốt cho bạn hạnh phúc, ngày xấu cho bạn kinh nghiệm.", author: "Khuyết danh" },
        { text: "Nếu bạn không thích điều gì đó, hãy thay đổi nó. Nếu bạn không thể thay đổi nó, hãy thay đổi thái độ của bạn.", author: "Maya Angelou" },
        { text: "Kẻ thù lớn nhất của thành công không phải là thất bại, mà là sự thỏa mãn.", author: "Education DevX" },
        { text: "Một tâm trí tĩnh lặng có thể giải quyết được những vấn đề hóc búa nhất.", author: "Khuyết danh" },
        { text: "Khi bạn tập trung vào điều tốt, điều tốt sẽ trở nên tốt hơn.", author: "Khuyết danh" },
        { text: "Mục đích lớn nhất của cuộc đời là sống một cuộc đời có mục đích.", author: "Robert Byrne" },
        { text: "Hãy để sự lựa chọn của bạn phản ánh hy vọng của bạn, chứ không phải nỗi sợ hãi của bạn.", author: "Nelson Mandela" },
        { text: "Người thầy thực sự là người giúp bạn tự tìm ra câu trả lời cho chính mình.", author: "Bruce Lee" },
        { text: "Kết quả của bạn ngày hôm nay là hệ quả của những thói quen bạn xây dựng trong 5 năm qua.", author: "Education DevX" }
    ];

    const quoteBox = document.getElementById('daily-quote-box');
    const quoteText = document.getElementById('quote-text');
    const quoteAuthor = document.getElementById('quote-author');

    if (quoteBox && !document.body.classList.contains('has-slide')) {
        const randomQuote = edevxQuotes[Math.floor(Math.random() * edevxQuotes.length)];
        quoteText.textContent = `"${randomQuote.text}"`;
        quoteAuthor.textContent = randomQuote.author;
        
        quoteBox.classList.remove('hidden'); 
        setTimeout(() => { quoteBox.classList.remove('opacity-0'); }, 150); 
    }
});