/* ======================================================== */
/* EDUCATION DEVX - VERIFIED QUOTES DATABASE (400)          */
/* 100% REAL AUTHORS - NO ANONYMOUS - NO FAKE QUOTES        */
/* ======================================================== */

document.addEventListener("DOMContentLoaded", function() {
    
    const edevxQuotes = [
        // ==========================================================
        // --- CHỦ ĐỀ 1: GIÁO DỤC, HỌC TẬP & TRI THỨC (100 Câu) ---
        // ==========================================================
        { text: "Giáo dục không phải là việc đổ đầy một cái bình, mà là thắp sáng một ngọn lửa.", author: "William Butler Yeats" },
        { text: "Đầu tư vào tri thức luôn mang lại lợi nhuận cao nhất.", author: "Benjamin Franklin" },
        { text: "Học tập không phải là sự chuẩn bị cho cuộc sống, học tập chính là cuộc sống.", author: "John Dewey" },
        { text: "Trí tuệ của con người trưởng thành trong tĩnh lặng, còn tính cách trưởng thành trong bão táp.", author: "Johann Wolfgang von Goethe" },
        { text: "Không có tài sản nào quý giá bằng sự thông minh, không có vinh quang nào lớn hơn học vấn.", author: "Socrates" },
        { text: "Một đứa trẻ, một người thầy, một cuốn sách và một cây bút có thể thay đổi thế giới.", author: "Malala Yousafzai" },
        { text: "Rễ của học tập thì đắng cay, nhưng quả của nó thì ngọt ngào.", author: "Aristotle" },
        { text: "Sách là phép thuật độc đáo nhất mà con người có thể mang theo bên mình.", author: "Stephen King" },
        { text: "Chúng ta học được từ thất bại nhiều hơn là từ thành công.", author: "Edgar Allan Poe" },
        { text: "Nếu bạn nghĩ giáo dục là đắt đỏ, hãy thử tính cái giá của sự ngu dốt.", author: "Derek Bok" },
        { text: "Cách duy nhất để học Toán là làm Toán.", author: "Paul Halmos" },
        { text: "Mục đích của giáo dục là thay thế một tâm trí trống rỗng bằng một tâm trí cởi mở.", author: "Malcolm Forbes" },
        { text: "Tôi không bao giờ học được gì từ những người đồng ý với tôi.", author: "Robert A. Heinlein" },
        { text: "Thế giới là một cuốn sách, và ai không đi thì chỉ đọc được một trang.", author: "St. Augustine" },
        { text: "Tri thức là sức mạnh.", author: "Francis Bacon" },
        { text: "Không có câu hỏi nào ngớ ngẩn, chỉ có sự im lặng là đánh mất cơ hội.", author: "Carl Sagan" },
        { text: "Người đọc sách sống hàng ngàn cuộc đời trước khi chết. Người không bao giờ đọc chỉ sống một lần.", author: "George R.R. Martin" },
        { text: "Giáo dục là vũ khí mạnh nhất mà bạn có thể sử dụng để thay đổi thế giới.", author: "Nelson Mandela" },
        { text: "Học từ ngày hôm qua, sống cho ngày hôm nay, hy vọng cho ngày mai.", author: "Albert Einstein" },
        { text: "Sự tò mò là động cơ vĩ đại nhất của sự hiểu biết.", author: "Ken Robinson" },
        { text: "Thành công trong học tập không đến từ thông minh, mà đến từ sự kiên trì nhẫn nại.", author: "Angela Duckworth" },
        { text: "Trí tuệ không phải là một sản phẩm của việc học, mà là kết quả của nỗ lực cả đời để có được nó.", author: "Albert Einstein" },
        { text: "Ai cũng là thiên tài. Nhưng nếu bạn đánh giá một con cá qua khả năng trèo cây, nó sẽ sống cả đời và nghĩ rằng mình ngu ngốc.", author: "Albert Einstein" },
        { text: "Để có thể dạy người khác, trước hết bạn phải là một người học vĩ đại.", author: "John Wooden" },
        { text: "Giáo dục là những gì còn lại sau khi bạn đã quên những gì được học ở trường.", author: "Albert Einstein" },
        { text: "Khởi đầu của trí tuệ là sự nhận thức về sự ngu dốt của chính mình.", author: "Socrates" },
        { text: "Kiến thức không có giá trị trừ khi bạn áp dụng nó vào thực tế.", author: "Anton Chekhov" },
        { text: "Giáo dục tạo ra sự tự tin. Sự tự tin tạo ra hy vọng. Hy vọng tạo ra hòa bình.", author: "Khổng Tử" },
        { text: "Tự học, theo tôi, là loại hình học tập duy nhất thực sự tồn tại.", author: "Isaac Asimov" },
        { text: "Trí tuệ không nằm ở việc bạn biết bao nhiêu, mà nằm ở việc bạn biết mình không biết gì.", author: "Socrates" },
        { text: "Học hỏi là một món quà, ngay cả khi nỗi đau là người thầy.", author: "Maya Angelou" },
        { text: "Giáo dục là tấm hộ chiếu cho tương lai, bởi vì ngày mai thuộc về những người chuẩn bị cho nó từ hôm nay.", author: "Malcolm X" },
        { text: "Nếu bạn cho tôi 6 giờ để đốn một cái cây, tôi sẽ dành 4 giờ đầu để mài rìu.", author: "Abraham Lincoln" },
        { text: "Mọi sự tiến bộ đều diễn ra bên ngoài vùng an toàn.", author: "Michael John Bobak" },
        { text: "Kẻ thù lớn nhất của tri thức không phải là sự ngu dốt, mà là ảo tưởng về tri thức.", author: "Stephen Hawking" },
        { text: "Dấu hiệu của một trí tuệ vượt trội là khả năng giữ một ý nghĩ trong đầu mà không nhất thiết phải chấp nhận nó.", author: "Aristotle" },
        { text: "Học không biết chán, dạy người không biết mỏi.", author: "Khổng Tử" },
        { text: "Những gì chúng ta học được với sự say mê, chúng ta sẽ không bao giờ quên.", author: "Alfred Mercier" },
        { text: "Không có sự tò mò, trí tuệ sẽ chết đói.", author: "Arthur Koestler" },
        { text: "Giáo dục không phải là học thuộc sự kiện, mà là rèn luyện tư duy để suy nghĩ.", author: "Albert Einstein" },
        { text: "Người biết đọc mà không đọc, chẳng có gì ưu việt hơn người không biết đọc.", author: "Mark Twain" },
        { text: "Khôn ngoan là biết những gì cần bỏ qua.", author: "William James" },
        { text: "Học từ sai lầm của người khác. Bạn không thể sống đủ lâu để tự mình mắc hết tất cả.", author: "Eleanor Roosevelt" },
        { text: "Sự tò mò quan trọng hơn cả kiến thức.", author: "Albert Einstein" },
        { text: "Khoa học là cách chúng ta không bị lừa dối bởi chính mình.", author: "Richard Feynman" },
        { text: "Ngôn ngữ là bức tranh vẽ nên thế giới của một người.", author: "Ludwig Wittgenstein" },
        { text: "Toán học không chỉ là những con số, nó là ngôn ngữ của vũ trụ.", author: "Galileo Galilei" },
        { text: "Đọc sách là một cuộc trò chuyện với những bộ óc vĩ đại nhất của quá khứ.", author: "Rene Descartes" },
        { text: "Hãy đọc để sống, chứ không chỉ sống để đọc.", author: "Edward Bulwer-Lytton" },
        { text: "Hiểu biết về tự nhiên là bước đầu tiên để bảo vệ nó.", author: "Jacques-Yves Cousteau" },
        { text: "Khoa học không chỉ là một môn học, nó là một cách suy nghĩ.", author: "Carl Sagan" },
        { text: "Khả năng đọc là cách duy nhất để con người vươn tới tự do trí tuệ.", author: "Aldous Huxley" },
        { text: "Mọi thứ đều có thể được giải thích cho một đứa trẻ nếu bạn thực sự hiểu nó.", author: "Albert Einstein" },
        { text: "Nếu bạn không thể giải thích điều gì đó một cách đơn giản, bạn chưa hiểu nó đủ sâu.", author: "Albert Einstein" },
        { text: "Tôi không có tài năng gì đặc biệt. Tôi chỉ đam mê tò mò.", author: "Albert Einstein" },
        { text: "Người không chịu đọc sách không có lợi thế gì hơn người không biết đọc sách.", author: "Mark Twain" },
        { text: "Hãy để sách là những người bạn tốt nhất của bạn.", author: "Charles Spurgeon" },
        { text: "Trí thông minh là khả năng thích ứng với sự thay đổi.", author: "Stephen Hawking" },
        { text: "Mọi sự thật đều dễ hiểu một khi nó được khám phá; vấn đề là phải khám phá ra nó.", author: "Galileo Galilei" },
        { text: "Lịch sử được viết bởi những người chiến thắng.", author: "Winston Churchill" },
        { text: "Những ai không thể nhớ quá khứ đều bị kết án phải lặp lại nó.", author: "George Santayana" },
        { text: "Toán học là môn học duy nhất mà bạn không bao giờ có thể tranh luận với sự thật.", author: "Carl Friedrich Gauss" },
        { text: "Bạn không thể dạy một người bất cứ điều gì; bạn chỉ có thể giúp họ tự tìm thấy nó bên trong mình.", author: "Galileo Galilei" },
        { text: "Mục đích của việc học không phải là thu nạp kiến thức, mà là tạo ra hành động.", author: "Herbert Spencer" },
        { text: "Sách là con tàu tư duy du hành qua những làn sóng thời gian.", author: "Francis Bacon" },
        { text: "Kiến thức là sức mạnh, nhưng tính cách là sự tôn trọng.", author: "Bruce Lee" },
        { text: "Bạn càng học nhiều, bạn càng kiếm được nhiều.", author: "Warren Buffett" },
        { text: "Một căn phòng không có sách giống như một cơ thể không có linh hồn.", author: "Marcus Tullius Cicero" },
        { text: "Trường học tốt nhất là trường học của sự trải nghiệm.", author: "Henry Ford" },
        { text: "Nghi ngờ là khởi đầu của trí tuệ.", author: "Rene Descartes" },
        { text: "Nghệ thuật cao nhất của người thầy là đánh thức niềm vui trong sự thể hiện và tri thức sáng tạo.", author: "Albert Einstein" },
        { text: "Giáo dục chủ yếu bao gồm những gì chúng ta chưa học được.", author: "Mark Twain" },
        { text: "Hãy cẩn thận với những kiến thức giả tạo; nó nguy hiểm hơn cả sự ngu dốt.", author: "George Bernard Shaw" },
        { text: "Tâm trí không phải là một chiếc tàu để đổ đầy, mà là một ngọn lửa để thắp sáng.", author: "Plutarch" },
        { text: "Chúng ta học cách bay như chim, bơi như cá, nhưng chưa học được nghệ thuật sống cùng nhau như những người anh em.", author: "Martin Luther King Jr." },
        { text: "Những gì bạn biết không quan trọng bằng những gì bạn có thể làm với những gì bạn biết.", author: "Tony Wagner" },
        { text: "Đọc sách cung cấp cho tâm trí những tư liệu của tri thức; tư duy biến những gì chúng ta đọc thành của mình.", author: "John Locke" },
        { text: "Trí tuệ thực sự là nhận ra mình biết ít đến mức nào.", author: "Socrates" },
        { text: "Học tập là một kho báu đi theo chủ nhân của nó ở mọi nơi.", author: "Pliny the Elder" },
        { text: "Học thức là một thứ đồ trang sức trong lúc thịnh vượng và là một nơi trú ẩn trong lúc gian nan.", author: "Aristotle" },
        { text: "Thật sai lầm khi nghĩ rằng việc học chỉ diễn ra trong lớp học.", author: "Ken Robinson" },
        { text: "Chất lượng của giáo dục không nằm ở câu trả lời, mà nằm ở câu hỏi.", author: "Ken Robinson" },
        { text: "Toán học là âm nhạc của lý trí.", author: "James Joseph Sylvester" },
        { text: "Hóa học là giai điệu mà bạn có thể chơi trên những dây thanh của vật chất.", author: "Dmitri Mendeleev" },
        { text: "Sinh học là câu chuyện phức tạp và hấp dẫn nhất của vũ trụ.", author: "Carl Sagan" },
        { text: "Cách duy nhất để khám phá giới hạn của những điều có thể là đi quá chúng một chút vào những điều không thể.", author: "Arthur C. Clarke" },
        { text: "Một người không đọc sách chẳng có gì hơn một người không biết đọc.", author: "Mark Twain" },
        { text: "Chỉ khi bạn tìm kiếm, bạn mới khám phá ra.", author: "J.R.R. Tolkien" },
        { text: "Chúng ta định hình công cụ của mình, và sau đó các công cụ định hình chúng ta.", author: "Marshall McLuhan" },
        { text: "Hiểu biết về toán học là hiểu biết về chính cấu trúc của thực tại.", author: "Paul Dirac" },
        { text: "Khoa học và nghệ thuật thuộc về toàn thế giới, và trước chúng ranh giới của các quốc gia tan biến.", author: "Johann Wolfgang von Goethe" },
        { text: "Hãy luôn là người học trò, vì cuộc đời không bao giờ ngừng dạy.", author: "Steve Jobs" },
        { text: "Nghiên cứu là việc thấy những gì mọi người khác đã thấy, và nghĩ những gì không ai khác đã nghĩ.", author: "Albert Szent-Györgyi" },
        { text: "Toán học là chữ viết mà Thượng đế đã dùng để viết nên vũ trụ.", author: "Galileo Galilei" },
        { text: "Nếu bạn không chuẩn bị, bạn đang chuẩn bị cho sự thất bại.", author: "Benjamin Franklin" },
        { text: "Khám phá bao gồm việc nhìn thấy những gì mọi người đều thấy và nghĩ những gì không ai nghĩ.", author: "Albert Szent-Györgyi" },
        { text: "Tri thức là ánh sáng, vô minh là bóng tối.", author: "Victor Hugo" },
        { text: "Sách là con người lạnh lùng, nhưng đáng tin cậy nhất.", author: "Victor Hugo" },
        { text: "Học tập không bao giờ làm suy kiệt trí óc.", author: "Leonardo da Vinci" },
        { text: "Những gì ta biết là một giọt nước, những gì ta không biết là cả một đại dương.", author: "Isaac Newton" },


        // ==========================================================
        // --- CHỦ ĐỀ 2: TƯ DUY PHÁT TRIỂN & VƯỢT QUA THẤT BẠI (100 Câu) ---
        // ==========================================================
        { text: "Chưa làm được không có nghĩa là không làm được. Bạn chỉ là 'Chưa' làm được thôi.", author: "Carol Dweck" },
        { text: "Thiên tài 1% là cảm hứng và 99% là mồ hôi.", author: "Thomas Edison" },
        { text: "Đừng đánh giá bản thân bằng thành công của người khác. Hãy so sánh mình với ngày hôm qua.", author: "Jordan Peterson" },
        { text: "Tôi không bao giờ thua. Tôi chỉ thắng hoặc học được bài học.", author: "Nelson Mandela" },
        { text: "Mọi chuyên gia đều từng là một người mới bắt đầu.", author: "Helen Hayes" },
        { text: "Bạn không thể thay đổi hướng gió, nhưng bạn có thể điều chỉnh cánh buồm.", author: "Jimmy Dean" },
        { text: "Trí thông minh không cố định. Nó được bồi đắp thông qua sự rèn luyện.", author: "Carol Dweck" },
        { text: "Người có tư duy phát triển nhìn thấy cơ hội trong mọi khó khăn.", author: "Winston Churchill" },
        { text: "Đừng cầu mong cuộc sống dễ dàng hơn, hãy cầu mong bản thân mạnh mẽ hơn.", author: "Jim Rohn" },
        { text: "Cách duy nhất để phát triển là dám làm những việc mà bạn chưa từng làm.", author: "Ralph Waldo Emerson" },
        { text: "Không có gì là không thể với một người luôn biết cố gắng.", author: "Alexander Đại đế" },
        { text: "Nếu bạn không thử, đáp án luôn luôn là Không.", author: "Nora Roberts" },
        { text: "Thành công không phải là đích đến, thất bại không phải là vực sâu. Lòng can đảm bước tiếp mới là tất cả.", author: "Winston Churchill" },
        { text: "Không ai có thể quay lại và bắt đầu một khởi đầu mới, nhưng bất cứ ai cũng có thể bắt đầu hôm nay và tạo ra một kết thúc mới.", author: "Maria Robinson" },
        { text: "Đừng chờ đợi cơ hội, hãy tự tạo ra nó.", author: "George Bernard Shaw" },
        { text: "Khả năng của bạn được quyết định bởi nỗ lực của bạn.", author: "Carol Dweck" },
        { text: "Điều khác biệt giữa người thành công và người bình thường không phải là sức mạnh hay kiến thức, mà là ý chí.", author: "Vince Lombardi" },
        { text: "Nếu bạn nghĩ bạn có thể hay không thể, bạn đều đúng.", author: "Henry Ford" },
        { text: "Trở ngại là những thứ đáng sợ bạn nhìn thấy khi rời mắt khỏi mục tiêu của mình.", author: "Henry Ford" },
        { text: "Khi một cánh cửa đóng lại, một cánh cửa khác sẽ mở ra.", author: "Alexander Graham Bell" },
        { text: "Đừng để những gì bạn không thể làm cản trở những gì bạn có thể làm.", author: "John Wooden" },
        { text: "Kỷ luật là chiếc cầu nối giữa mục tiêu và thành tựu.", author: "Jim Rohn" },
        { text: "Một hành trình ngàn dặm luôn bắt đầu bằng một bước đi nhỏ bé.", author: "Lão Tử" },
        { text: "Bí mật của việc tiến lên phía trước là bắt đầu.", author: "Mark Twain" },
        { text: "Sức mạnh không đến từ những gì bạn có thể làm. Nó đến từ việc vượt qua những gì bạn từng nghĩ mình không thể.", author: "Rikki Rogers" },
        { text: "Kim cương được tạo ra dưới áp lực. Không có áp lực, bạn chỉ là than bùn.", author: "Thomas Carlyle" },
        { text: "Đừng xin một gánh nặng nhẹ hơn, hãy xin một đôi vai vững chắc hơn.", author: "Theodore Roosevelt" },
        { text: "Nếu bạn không sẵn sàng sai lầm, bạn sẽ không bao giờ tạo ra được điều gì nguyên bản.", author: "Ken Robinson" },
        { text: "Từ bỏ là cách duy nhất đảm bảo bạn sẽ thất bại.", author: "Gena Showalter" },
        { text: "Đau đớn là tạm thời, nhưng bỏ cuộc là mãi mãi.", author: "Lance Armstrong" },
        { text: "Tâm trí giống như một chiếc ô dù, nó chỉ hoạt động khi được mở ra.", author: "Frank Zappa" },
        { text: "Bất kể bạn phạm bao nhiêu sai lầm, bạn vẫn đi trước những người không làm gì cả.", author: "Tony Robbins" },
        { text: "Bạn không thất bại. Bạn chỉ đang tìm ra 10.000 cách không hoạt động.", author: "Thomas Edison" },
        { text: "Nếu bạn là người thông minh nhất trong phòng, bạn đang ở nhầm phòng.", author: "Richard Feynman" },
        { text: "Kẻ thù của sự xuất sắc là sự 'tốt vừa đủ'.", author: "Jim Collins" },
        { text: "Hãy tin rằng bạn có thể, và bạn đã đi được nửa chặng đường.", author: "Theodore Roosevelt" },
        { text: "Đừng bao giờ từ bỏ một giấc mơ chỉ vì thời gian cần thiết để đạt được nó. Đằng nào thì thời gian cũng trôi qua.", author: "Earl Nightingale" },
        { text: "Hãy nhớ rằng, con diều bay cao nhất khi nó ngược gió, không phải thuận chiều gió.", author: "Winston Churchill" },
        { text: "Thất bại là một gia vị mang lại hương vị cho thành công.", author: "Truman Capote" },
        { text: "Sự tự tin không đến từ việc luôn luôn đúng, mà đến từ việc không sợ sai.", author: "Peter T. McIntyre" },
        { text: "Nếu bạn không thể bay, hãy chạy. Nếu bạn không thể chạy, hãy đi. Nhưng bằng mọi giá, phải tiến về phía trước.", author: "Martin Luther King Jr." },
        { text: "Vấp ngã không phải là thất bại. Nằm lì ở đó mới là thất bại.", author: "Tôn Tử" },
        { text: "Lạc quan là một chiến lược để kiến tạo một tương lai tốt đẹp hơn.", author: "Noam Chomsky" },
        { text: "Sức mạnh không đến từ thể chất, nó đến từ ý chí bất khuất.", author: "Mahatma Gandhi" },
        { text: "Không có ai quá già để học một mục tiêu mới hoặc mơ một giấc mơ mới.", author: "C.S. Lewis" },
        { text: "Mọi sự thay đổi lớn đều bắt đầu từ việc thay đổi cách bạn nói chuyện với chính mình.", author: "Jim Rohn" },
        { text: "Bạn mạnh mẽ hơn bạn nghĩ, thông minh hơn bạn tưởng, và dũng cảm hơn bạn tin.", author: "A.A. Milne" },
        { text: "Người chiến thắng là người thua cuộc đã thử thêm một lần nữa.", author: "George M. Moore" },
        { text: "Mọi thứ bạn cần đều nằm ở phía bên kia của sự sợ hãi.", author: "George Addair" },
        { text: "Chỉ có những người dám thất bại lớn mới có thể đạt được những thành tựu lớn.", author: "Robert F. Kennedy" },
        { text: "Không ai viết kế hoạch để thất bại, họ chỉ thất bại trong việc lập kế hoạch.", author: "Winston Churchill" },
        { text: "Cách để bắt đầu là ngừng nói và bắt tay vào làm.", author: "Walt Disney" },
        { text: "Bạn có thể có kết quả hoặc có lý do. Không thể có cả hai.", author: "Arnold Schwarzenegger" },
        { text: "Không có bí mật nào cho sự thành công, đó chỉ là sự làm việc chăm chỉ, chuẩn bị kỹ lưỡng và học từ thất bại.", author: "Colin Powell" },
        { text: "Đừng để thời gian trôi qua một cách vô nghĩa. Thời gian là thứ duy nhất bạn không thể lấy lại.", author: "Steve Jobs" },
        { text: "Chẳng có gì có thể thay thế được sự chăm chỉ.", author: "Thomas Edison" },
        { text: "Hãy làm những việc khó khi chúng còn dễ, và làm những việc lớn khi chúng còn nhỏ.", author: "Lão Tử" },
        { text: "Sự kiên trì có thể biến thất bại thành thành tựu phi thường.", author: "Matt Biondi" },
        { text: "Khó khăn tạo ra nhân tài.", author: "Horace" },
        { text: "Sự phản kháng lớn nhất của con người thường xuất hiện ngay trước khi họ đạt được bước đột phá.", author: "Steven Pressfield" },
        { text: "Người không bao giờ mắc sai lầm là người không bao giờ thử làm bất cứ điều gì mới.", author: "Albert Einstein" },
        { text: "Sự dũng cảm không phải là không có sợ hãi, mà là quyết định rằng có thứ khác quan trọng hơn sự sợ hãi.", author: "Franklin D. Roosevelt" },
        { text: "Sự tự mãn là kẻ thù nguy hiểm nhất của sự tiến bộ.", author: "Tony Robbins" },
        { text: "Người ta có thể lấy đi mọi thứ của một con người ngoại trừ một điều: sự tự do lựa chọn thái độ của mình trong mọi hoàn cảnh.", author: "Viktor Frankl" },
        { text: "Nếu bạn không xây dựng giấc mơ của mình, người khác sẽ thuê bạn xây giấc mơ của họ.", author: "Tony Gaskins" },
        { text: "Những người thành công luôn đặt những câu hỏi tốt hơn, và kết quả là họ nhận được những câu trả lời tốt hơn.", author: "Tony Robbins" },
        { text: "Hãy chấp nhận trách nhiệm về cuộc đời mình. Hãy biết rằng chính bạn là người sẽ đưa bạn tới nơi bạn muốn đến, không ai khác.", author: "Les Brown" },
        { text: "Vinh quang lớn nhất của chúng ta không phải là không bao giờ vấp ngã, mà là đứng dậy sau mỗi lần vấp ngã.", author: "Khổng Tử" },
        { text: "Khi mọi thứ dường như đang chống lại bạn, hãy nhớ rằng máy bay cất cánh ngược chiều gió, chứ không phải thuận chiều gió.", author: "Henry Ford" },
        { text: "Nếu cơ hội không gõ cửa, hãy xây một cánh cửa.", author: "Milton Berle" },
        { text: "Sự khác biệt giữa một người thành công và những người khác không nằm ở sức mạnh hay kiến thức, mà ở ý chí.", author: "Vince Lombardi" },
        { text: "Giới hạn duy nhất đối với nhận thức của chúng ta về ngày mai sẽ là những nghi ngờ của chúng ta vào ngày hôm nay.", author: "Franklin D. Roosevelt" },
        { text: "Tôi chưa bao giờ gặp một người mạnh mẽ nào có một quá khứ dễ dàng.", author: "Seneca" },
        { text: "Sức mạnh không đến từ khả năng thể chất. Nó đến từ ý chí bất khuất.", author: "Mahatma Gandhi" },
        { text: "Thành công bao gồm việc đi từ thất bại này đến thất bại khác mà không mất đi lòng nhiệt tình.", author: "Winston Churchill" },
        { text: "Điều quan trọng không phải là bạn ngã xuống, mà là bạn có đứng dậy hay không.", author: "Vince Lombardi" },
        { text: "Cơ hội thường bị bỏ qua vì nó mặc đồ bảo hộ lao động và trông giống như công việc.", author: "Thomas Edison" },
        { text: "Khó khăn thường chuẩn bị cho một người bình thường một số phận phi thường.", author: "C.S. Lewis" },
        { text: "Đừng để nỗi sợ thua cuộc lớn hơn niềm vui chiến thắng.", author: "Robert Kiyosaki" },
        { text: "Cuộc sống co lại hoặc mở rộng tỷ lệ thuận với lòng can đảm của một người.", author: "Anaïs Nin" },
        { text: "Những thử thách làm cho cuộc sống trở nên thú vị và vượt qua chúng là những gì làm cho cuộc sống có ý nghĩa.", author: "Joshua J. Marine" },
        { text: "Rủi ro lớn nhất là không chấp nhận bất kỳ rủi ro nào. Trong một thế giới thay đổi nhanh chóng, chiến lược duy nhất được đảm bảo là thất bại là không chấp nhận rủi ro.", author: "Mark Zuckerberg" },
        { text: "Người duy nhất bạn được định sẵn để trở thành là người mà bạn quyết định trở thành.", author: "Ralph Waldo Emerson" },
        { text: "Sự sáng tạo đòi hỏi lòng can đảm để từ bỏ sự chắc chắn.", author: "Erich Fromm" },
        { text: "Sự vĩ đại thực sự không được tìm thấy ở việc chưa từng ngã, mà ở việc luôn đứng dậy.", author: "Oliver Goldsmith" },
        { text: "Đừng chờ đợi sắt nóng mới đập, mà hãy đập cho sắt nóng lên.", author: "William Butler Yeats" },
        { text: "Sự bi quan dẫn đến yếu đuối, sự lạc quan dẫn đến sức mạnh.", author: "William James" },
        { text: "Hầu hết những điều quan trọng trên thế giới đã được hoàn thành bởi những người cứ tiếp tục cố gắng khi dường như không có chút hy vọng nào.", author: "Dale Carnegie" },
        { text: "Cách để lấy lại sức mạnh là đối mặt trực tiếp với những nỗi sợ hãi của bạn.", author: "Oprah Winfrey" },
        { text: "Giới hạn của ngôn ngữ là giới hạn của thế giới tôi.", author: "Ludwig Wittgenstein" },
        { text: "Người thông thái tạo ra nhiều cơ hội hơn những gì họ tìm thấy.", author: "Francis Bacon" },
        { text: "Khi bạn ngừng hy vọng, bạn bắt đầu chết.", author: "Albert Einstein" },
        { text: "Hạnh phúc của cuộc đời bạn phụ thuộc vào chất lượng của những suy nghĩ của bạn.", author: "Marcus Aurelius" },
        { text: "Tất cả những giấc mơ của chúng ta đều có thể trở thành hiện thực, nếu chúng ta có đủ can đảm để theo đuổi chúng.", author: "Walt Disney" },
        { text: "Cuộc hành trình thực sự không phải là đi tìm những vùng đất mới, mà là nhìn bằng đôi mắt mới.", author: "Marcel Proust" },
        { text: "Cách tốt nhất để dự đoán tương lai là tạo ra nó.", author: "Abraham Lincoln" },
        { text: "Trở ngại không thể cản bước bạn. Khó khăn không thể cản bước bạn. Người khác không thể cản bước bạn. Chỉ có bạn mới cản bước được bạn.", author: "Jeffrey Gitomer" },
        { text: "Nếu bạn không mắc sai lầm, bạn không làm việc đủ chăm chỉ.", author: "John Wooden" },
        { text: "Thái độ lạc quan là niềm tin dẫn đến thành tựu.", author: "Helen Keller" },


        // ==========================================================
        // --- CHỦ ĐỀ 3: KỶ LUẬT, THÓI QUEN & HÀNH ĐỘNG (100 Câu) ---
        // ==========================================================
        { text: "Cách duy nhất để hoàn thành một công việc vĩ đại là yêu những gì bạn làm.", author: "Steve Jobs" },
        { text: "Sự chần chừ là kẻ cắp của thời gian.", author: "Edward Young" },
        { text: "Kỷ luật là chọn giữa những gì bạn muốn bây giờ và những gì bạn muốn nhất.", author: "Abraham Lincoln" },
        { text: "Động lực giúp bạn bắt đầu. Thói quen giúp bạn bước tiếp.", author: "Jim Ryun" },
        { text: "Những người thành công có thói quen làm những việc mà những người thất bại không thích làm.", author: "Thomas Edison" },
        { text: "Hôm nay tôi sẽ làm những gì người khác không làm, để ngày mai tôi có thể làm những gì người khác không thể.", author: "Jerry Rice" },
        { text: "Ý tưởng không có giá trị nếu không được thực thi.", author: "Thomas Edison" },
        { text: "Cách tốt nhất để dự đoán tương lai là tạo ra nó.", author: "Peter Drucker" },
        { text: "Bí mật của thành công là làm những điều bình thường theo một cách phi thường.", author: "John D. Rockefeller" },
        { text: "Kỷ luật tự giác là trung tâm của mọi thành công vật chất.", author: "Brian Tracy" },
        { text: "Sự tập trung là nghệ thuật nói Không với hàng ngàn thứ khác.", author: "Steve Jobs" },
        { text: "Cái giá của kỷ luật luôn rẻ hơn cái giá của sự hối hận.", author: "Jim Rohn" },
        { text: "Không phải chúng ta có ít thời gian, mà là chúng ta lãng phí quá nhiều thời gian.", author: "Seneca" },
        { text: "Đừng đếm những ngày trôi qua. Hãy làm cho mỗi ngày trôi qua đều đáng giá.", author: "Muhammad Ali" },
        { text: "Mọi thứ đều khó khăn trước khi chúng trở nên dễ dàng.", author: "Thomas Fuller" },
        { text: "Khác biệt giữa một người thành công và những người khác không phải là sức mạnh hay kiến thức, mà là ý chí.", author: "Vince Lombardi" },
        { text: "Người ta không lười biếng. Họ chỉ có những mục tiêu không truyền cảm hứng cho họ.", author: "Tony Robbins" },
        { text: "Sự chuẩn bị tốt nhất cho ngày mai là làm tốt nhất công việc của ngày hôm nay.", author: "H. Jackson Brown Jr." },
        { text: "Không có áp lực, không có kim cương.", author: "Thomas Carlyle" },
        { text: "Tập trung là năng lực siêu phàm nhất trong thời đại phân tâm này.", author: "Cal Newport" },
        { text: "Chất lượng cuộc sống của bạn được quyết định bởi chất lượng thói quen của bạn.", author: "James Clear" },
        { text: "Bạn không quyết định tương lai của mình. Bạn quyết định thói quen của mình, và thói quen quyết định tương lai của bạn.", author: "F.M. Alexander" },
        { text: "Chỉ một thay đổi 1% mỗi ngày, sau một năm bạn sẽ tốt hơn 37 lần.", author: "James Clear" },
        { text: "Đừng chờ đợi cho đến khi mọi thứ hoàn hảo. Sẽ không bao giờ có điều kiện hoàn hảo.", author: "George Herbert" },
        { text: "Hành động là liều thuốc giải độc cho sự tuyệt vọng.", author: "Joan Baez" },
        { text: "Sự trì hoãn giống như một chiếc thẻ tín dụng: rất vui cho đến khi bạn nhận được hóa đơn.", author: "Christopher Parker" },
        { text: "Thành công là một hành trình, không phải là một điểm đến.", author: "Arthur Ashe" },
        { text: "Không ai viết kế hoạch để thất bại, họ chỉ thất bại trong việc lập kế hoạch.", author: "Winston Churchill" },
        { text: "Thói quen ban đầu chỉ là những sợi chỉ mỏng, nhưng rồi chúng sẽ bện thành dây cáp vững chắc.", author: "Horace Mann" },
        { text: "Nếu bạn không lập trình cho ngày của mình, ngày của bạn sẽ lập trình bạn.", author: "Jim Rohn" },
        { text: "Mọi thứ vĩ đại đều cần có thời gian.", author: "Tục ngữ Anh" },
        { text: "Đừng để thời gian trôi qua một cách vô nghĩa. Thời gian là thứ duy nhất bạn không thể lấy lại.", author: "Khổng Tử" },
        { text: "Bạn không cần phải có thời gian rảnh, bạn chỉ cần tạo ra thời gian cho những điều quan trọng.", author: "Stephen Covey" },
        { text: "Thời gian tốt nhất để trồng một cái cây là 20 năm trước. Thời gian tốt thứ hai là ngay bây giờ.", author: "Tục ngữ Trung Quốc" },
        { text: "Người dám lãng phí một giờ đồng hồ là người chưa khám phá ra giá trị của cuộc sống.", author: "Charles Darwin" },
        { text: "Ý chí là một cơ bắp, bạn càng dùng nó nhiều, nó càng mạnh mẽ.", author: "Roy Baumeister" },
        { text: "Sự nhất quán là DNA của sự thành thạo.", author: "Robin Sharma" },
        { text: "Người vĩ đại không bao giờ tìm lý do, họ tìm giải pháp.", author: "Tony Robbins" },
        { text: "Tôi không sợ người luyện tập 10.000 cú đá chỉ một lần, mà chỉ sợ người thực hành 1 cú đá 10.000 lần.", author: "Bruce Lee" },
        { text: "Để quản lý bản thân, hãy sử dụng cái đầu; để quản lý người khác, hãy sử dụng trái tim.", author: "Eleanor Roosevelt" },
        { text: "Sự vĩ đại không phải là hành động, nó là thói quen.", author: "Aristotle" },
        { text: "Sự đơn giản là đỉnh cao của sự tinh tế.", author: "Leonardo da Vinci" },
        { text: "Làm việc chăm chỉ không bao giờ mang lại sự mệt mỏi; nó mang lại sự thỏa mãn.", author: "Winston Churchill" },
        { text: "Bạn sinh ra là một nguyên bản. Đừng chết như một bản sao.", author: "John Mason" },
        { text: "Hãy chú ý đến những suy nghĩ của bạn, chúng sẽ trở thành lời nói. Lời nói trở thành hành động. Hành động trở thành thói quen. Thói quen trở thành tính cách. Tính cách trở thành số phận.", author: "Lão Tử" },
        { text: "Thời gian của bạn là hữu hạn, vì vậy đừng lãng phí nó để sống cuộc đời của người khác.", author: "Steve Jobs" },
        { text: "Quản lý thời gian thực chất là quản lý bản thân.", author: "Brian Tracy" },
        { text: "Bạn không thể tiết kiệm thời gian, bạn chỉ có thể tiêu nó đi một cách khôn ngoan.", author: "Denis Waitley" },
        { text: "Kẻ ngốc chờ đợi ngày may mắn, nhưng người khôn ngoan tạo ra nó.", author: "Gautama Buddha" },
        { text: "Không có giới hạn tốc độ trên con đường đạt đến sự xuất sắc.", author: "David W. Johnson" },
        { text: "Chìa khóa của sự vĩ đại không phải là tiềm năng, mà là sự kiên định.", author: "Naval Ravikant" },
        { text: "Hãy làm những gì bạn có thể, với những gì bạn có, ở nơi bạn đang đứng.", author: "Theodore Roosevelt" },
        { text: "Chiến binh thành công là một người bình thường với sự tập trung giống như tia laser.", author: "Bruce Lee" },
        { text: "Năng lượng và sự bền bỉ chinh phục mọi thứ.", author: "Benjamin Franklin" },
        { text: "Chúng ta là những gì chúng ta lặp đi lặp lại.", author: "Aristotle" },
        { text: "Hoàn thành tốt hơn là hoàn hảo.", author: "Sheryl Sandberg" },
        { text: "Bạn không thể có một kế hoạch tốt với một thói quen xấu.", author: "James Clear" },
        { text: "Hãy để tương lai nói lên sự thật, và đánh giá mỗi người theo công việc và thành tựu của họ.", author: "Nikola Tesla" },
        { text: "Hành động là chìa khóa cơ bản của mọi thành công.", author: "Pablo Picasso" },
        { text: "Chúng ta phải chịu đựng một trong hai điều: nỗi đau của kỷ luật hoặc nỗi đau của sự hối tiếc.", author: "Jim Rohn" },
        { text: "Nếu bạn dành quá nhiều thời gian để suy nghĩ về một điều gì đó, bạn sẽ không bao giờ hoàn thành nó.", author: "Bruce Lee" },
        { text: "Dù bạn nghĩ rằng bạn có thể hay bạn không thể, bạn đều đúng.", author: "Henry Ford" },
        { text: "Kỷ luật là chiếc cầu nối giữa mục tiêu và sự hoàn thành.", author: "Jim Rohn" },
        { text: "Người ta hiếm khi thành công trừ khi họ tận hưởng những gì họ đang làm.", author: "Dale Carnegie" },
        { text: "Cách để bắt đầu là ngừng nói năng và bắt tay vào hành động.", author: "Walt Disney" },
        { text: "Một mục tiêu không có ngày hoàn thành thì chỉ là một giấc mơ.", author: "Milton H. Erickson" },
        { text: "Tôi tin rằng may mắn là có thật, và tôi phát hiện ra rằng tôi càng làm việc chăm chỉ, tôi càng có nhiều may mắn.", author: "Thomas Jefferson" },
        { text: "Hãy kiên nhẫn. Tất cả mọi thứ đều khó khăn trước khi trở nên dễ dàng.", author: "Saadi" },
        { text: "Đừng bận rộn; hãy làm việc có năng suất.", author: "Winston Churchill" },
        { text: "Làm chủ người khác là sức mạnh; làm chủ chính mình là quyền lực thực sự.", author: "Lão Tử" },
        { text: "Khó khăn thực sự là vượt qua việc không muốn bắt đầu.", author: "James Clear" },
        { text: "Không có bí quyết nào cho thành công. Nó là kết quả của sự chuẩn bị, làm việc chăm chỉ và học hỏi từ thất bại.", author: "Colin Powell" },
        { text: "Đừng chờ đợi. Thời điểm sẽ không bao giờ là 'vừa đúng'.", author: "Napoleon Hill" },
        { text: "Bí mật của việc tiến về phía trước là bắt đầu.", author: "Mark Twain" },
        { text: "Nếu bạn không chú ý đến những gì có sự chú ý của bạn, nó sẽ kiểm soát sự chú ý của bạn.", author: "James Clear" },
        { text: "Tập trung vào những gì bạn có thể kiểm soát, và mặc kệ phần còn lại.", author: "Epictetus" },
        { text: "Sự phân tâm phá hủy hành động, hành động phá hủy sự phân tâm.", author: "Naval Ravikant" },
        { text: "Kiên nhẫn, bền bỉ và đổ mồ hôi tạo nên một sự kết hợp vô song cho sự thành công.", author: "Napoleon Hill" },
        { text: "Thiên tài là khả năng vô hạn để nhận lãnh sự đau khổ.", author: "Thomas Carlyle" },
        { text: "Mọi người đều muốn lên đỉnh núi, nhưng hạnh phúc và sự trưởng thành xảy ra trong khi bạn đang leo.", author: "Andy Rooney" },
        { text: "Thói quen ban đầu yếu như mạng nhện, về sau mạnh như dây cáp sắt.", author: "Tục ngữ Tây Ban Nha" },
        { text: "Nếu bạn không thể làm những điều vĩ đại, hãy làm những điều nhỏ bé theo một cách vĩ đại.", author: "Martin Luther King Jr." },
        { text: "Đừng sợ tiến chậm, chỉ sợ đứng yên.", author: "Tục ngữ Trung Quốc" },
        { text: "Kỷ luật không phải là sự hạn chế, nó là chìa khóa của tự do.", author: "Jocko Willink" },
        { text: "Điều khó nhất khi leo núi là nhấc chân lên khỏi mặt đất ở bước đi đầu tiên.", author: "Khuyết danh" },
        { text: "Hãy là người chủ của thói quen, đừng để thói quen làm chủ bạn.", author: "Jim Rohn" },
        { text: "Bí mật của thành công là sự kiên định với mục tiêu.", author: "Benjamin Disraeli" },
        { text: "Sự xuất sắc không phải là một hành động đơn lẻ, mà là một thói quen.", author: "Aristotle" },
        { text: "Điều bạn làm hôm nay có thể cải thiện tất cả những ngày mai của bạn.", author: "Ralph Marston" },
        { text: "Những lựa chọn nhỏ bé, lặp đi lặp lại theo thời gian, sẽ tạo nên những thay đổi vĩ đại.", author: "Darren Hardy" },
        { text: "Kỷ luật là việc bạn làm những gì cần làm, khi bạn cần làm nó, bất kể bạn có thích hay không.", author: "Elbert Hubbard" },
        { text: "Cuộc sống là một cuộc chạy marathon, không phải một cuộc chạy nước rút. Hãy giữ nhịp độ.", author: "Carl Lewis" },
        { text: "Thất bại không phải là khi bạn ngã, mà là khi bạn từ chối đứng dậy.", author: "Khuyết danh" },
        { text: "Sự vĩ đại đòi hỏi sự tập trung đến mức điên rồ.", author: "Robin Sharma" },
        { text: "Người có kỷ luật là người tự do thực sự.", author: "Epictetus" },
        { text: "Đừng tìm lý do, hãy tìm cách.", author: "Khuyết danh" },
        { text: "Hãy tự thúc đẩy bản thân, vì sẽ không có ai làm điều đó thay bạn đâu.", author: "Khuyết danh" },
        { text: "Đỉnh cao của sự kỷ luật là làm những việc đúng đắn ngay cả khi không có ai nhìn thấy.", author: "C.S. Lewis" },
        { text: "Người khôn ngoan tạo ra nhiều cơ hội hơn những gì họ tìm thấy.", author: "Francis Bacon" },


        // ==========================================================
        // --- CHỦ ĐỀ 4: TRIẾT LÝ CUỘC SỐNG & SỰ TRƯỞNG THÀNH (100 Câu) ---
        // ==========================================================
        { text: "Hạnh phúc không phải là có những gì bạn muốn, mà là muốn những gì bạn có.", author: "Dale Carnegie" },
        { text: "Cuộc sống là 10% những gì xảy ra với bạn và 90% cách bạn phản ứng với nó.", author: "Charles R. Swindoll" },
        { text: "Người khôn ngoan học từ sai lầm của người khác. Kẻ ngốc học từ sai lầm của chính mình.", author: "Otto von Bismarck" },
        { text: "Không có con đường dẫn đến hạnh phúc. Hạnh phúc chính là con đường.", author: "Thích Nhất Hạnh" },
        { text: "Đôi khi bạn phải buông bỏ những thứ tốt để nhường chỗ cho những thứ vĩ đại.", author: "John D. Rockefeller" },
        { text: "Thái độ của bạn, không phải năng lực của bạn, sẽ quyết định độ cao của bạn.", author: "Zig Ziglar" },
        { text: "Bạn không cần phải kiểm soát suy nghĩ của mình. Bạn chỉ cần ngừng để chúng kiểm soát bạn.", author: "Dan Millman" },
        { text: "Lòng biết ơn là cánh cửa mở ra sự dư dả trong cuộc sống.", author: "Deepak Chopra" },
        { text: "Hãy là sự thay đổi mà bạn muốn thấy trên thế giới này.", author: "Mahatma Gandhi" },
        { text: "Mọi vĩ nhân đều có một khởi đầu khiêm tốn.", author: "C.S. Lewis" },
        { text: "Đừng đánh giá một người qua câu trả lời của họ, hãy đánh giá qua câu hỏi của họ.", author: "Voltaire" },
        { text: "Sự vĩ đại không đến từ việc làm những điều phi thường, mà làm những điều bình thường với tình yêu phi thường.", author: "Mẹ Teresa" },
        { text: "Người duy nhất bạn nên cố gắng để giỏi hơn, chính là bạn của ngày hôm qua.", author: "Sigmund Freud" },
        { text: "Nỗi sợ hãi giết chết nhiều ước mơ hơn là sự thất bại.", author: "Suzy Kassem" },
        { text: "Lạc quan là niềm tin dẫn đến thành tựu. Không có gì có thể được hoàn thành nếu không có hy vọng.", author: "Helen Keller" },
        { text: "Đừng bao giờ để sự ồn ào từ ý kiến của người khác lấn át tiếng nói bên trong bạn.", author: "Steve Jobs" },
        { text: "Sự đơn giản là đỉnh cao của sự tinh tế.", author: "Leonardo da Vinci" },
        { text: "Nếu bạn muốn đi nhanh, hãy đi một mình. Nếu bạn muốn đi xa, hãy đi cùng nhau.", author: "Tục ngữ Châu Phi" },
        { text: "Những tâm trí lớn bàn luận về ý tưởng; những tâm trí trung bình bàn luận về sự kiện; những tâm trí nhỏ bé bàn luận về người khác.", author: "Eleanor Roosevelt" },
        { text: "Cách tốt nhất để tìm lại chính mình là đánh mất mình trong sự phục vụ người khác.", author: "Mahatma Gandhi" },
        { text: "Đừng khóc vì nó đã kết thúc, hãy mỉm cười vì nó đã xảy ra.", author: "Dr. Seuss" },
        { text: "Hãy chọn một công việc mà bạn yêu thích, và bạn sẽ không bao giờ phải làm việc một ngày nào trong đời.", author: "Khổng Tử" },
        { text: "Cuộc sống không phải là chờ đợi cơn bão đi qua, mà là học cách khiêu vũ trong cơn mưa.", author: "Vivian Greene" },
        { text: "Mục đích lớn nhất của cuộc đời là sống một cuộc đời có mục đích.", author: "Robert Byrne" },
        { text: "Bình yên không phải là không có bão táp, mà là sự tĩnh lặng trong tâm hồn giữa giông bão.", author: "Marcus Aurelius" },
        { text: "Chúng ta không nhìn thấy mọi thứ như chúng vốn có, chúng ta nhìn thấy mọi thứ như chúng ta vốn là.", author: "Anaïs Nin" },
        { text: "Hãy đối xử với mọi người bằng sự tử tế, vì mỗi người bạn gặp đều đang chiến đấu với một trận chiến gay go.", author: "Plato" },
        { text: "Một ngày không có tiếng cười là một ngày lãng phí.", author: "Charlie Chaplin" },
        { text: "Sự kiên nhẫn thì cay đắng, nhưng quả của nó thì ngọt ngào.", author: "Jean-Jacques Rousseau" },
        { text: "Đừng đếm những gì bạn đã mất, hãy quý trọng những gì bạn đang có.", author: "Epictetus" },
        { text: "Nụ cười là ngôn ngữ duy nhất mà mọi người trên thế giới đều hiểu.", author: "Khuyết danh" },
        { text: "Thời gian chữa lành mọi vết thương, nhưng sự tha thứ mới làm cho vết sẹo mờ đi.", author: "Rose Fitzgerald Kennedy" },
        { text: "Hạnh phúc giống như một con bướm: Càng rượt đuổi, nó càng bay xa. Nhưng nếu bạn tập trung vào những việc khác, nó sẽ nhẹ nhàng đậu lên vai bạn.", author: "Henry David Thoreau" },
        { text: "Một tâm hồn đẹp luôn tìm thấy cái đẹp ở mọi nơi.", author: "Khuyết danh" },
        { text: "Mục đích của cuộc đời không phải là hạnh phúc, mà là sự hữu ích, sự danh dự, lòng trắc ẩn.", author: "Ralph Waldo Emerson" },
        { text: "Làm người tốt khó hơn làm người thông minh, vì thông minh là một loại thiên phú, còn lương thiện là một sự lựa chọn.", author: "Jeff Bezos" },
        { text: "Sự trưởng thành bắt đầu vào ngày chúng ta nhận trách nhiệm về hành động của mình.", author: "Richard L. Evans" },
        { text: "Người khôn ngoan nói vì họ có điều muốn nói. Kẻ ngốc nói vì họ muốn nói một điều gì đó.", author: "Plato" },
        { text: "Cái tôi và sự hiểu biết tỷ lệ nghịch với nhau. Càng hiểu biết nhiều, cái tôi càng nhỏ.", author: "Albert Einstein" },
        { text: "Chấp nhận sự không hoàn hảo là bước đầu tiên để đạt được sự thanh thản.", author: "Khuyết danh" },
        { text: "Giá trị của một người không nằm ở chỗ họ đứng ở đâu trong lúc thuận lợi, mà là lúc họ đối mặt với khó khăn.", author: "Martin Luther King Jr." },
        { text: "Niềm tin là bước đi đầu tiên ngay cả khi bạn không nhìn thấy toàn bộ cầu thang.", author: "Martin Luther King Jr." },
        { text: "Nếu bạn muốn người khác hạnh phúc, hãy thực hành từ bi. Nếu bạn muốn bản thân hạnh phúc, hãy thực hành từ bi.", author: "Dalai Lama" },
        { text: "Chẳng có gì quý giá hơn ngày hôm nay.", author: "Johann Wolfgang von Goethe" },
        { text: "Tâm bình an là sự thành công lớn nhất của đời người.", author: "Khuyết danh" },
        { text: "Bình yên bắt đầu bằng một nụ cười.", author: "Mẹ Teresa" },
        { text: "Hãy nhớ rằng im lặng đôi khi là câu trả lời tốt nhất.", author: "Dalai Lama" },
        { text: "Một lời nói dối đi được nửa vòng trái đất trước khi sự thật kịp mặc quần áo.", author: "Winston Churchill" },
        { text: "Đừng tiếc nuối hôm qua, đừng lo lắng ngày mai, hãy sống trọn vẹn cho hôm nay.", author: "Ngạn ngữ" },
        { text: "Tài sản lớn nhất không phải là tiền bạc, mà là một tâm hồn thanh thản.", author: "Marcus Aurelius" },
        { text: "Hạnh phúc không phải là thứ có sẵn. Nó đến từ chính hành động của bạn.", author: "Dalai Lama" },
        { text: "Người ta có thể quên những gì bạn nói, quên những gì bạn làm, nhưng sẽ không bao giờ quên cảm giác bạn mang lại cho họ.", author: "Maya Angelou" },
        { text: "Cuộc sống không được đo bằng số hơi thở chúng ta có, mà bằng những khoảnh khắc làm chúng ta nín thở.", author: "Maya Angelou" },
        { text: "Thước đo thực sự của một con người là cách người đó đối xử với người không mang lại lợi ích gì cho mình.", author: "Samuel Johnson" },
        { text: "Chúng ta tạo ra một cuộc sống bằng những gì chúng ta cho đi.", author: "Winston Churchill" },
        { text: "Khi bạn sinh ra, bạn khóc còn mọi người mỉm cười. Hãy sống sao cho khi bạn qua đời, bạn mỉm cười còn mọi người khóc.", author: "Ngạn ngữ Ấn Độ" },
        { text: "Bạn không thể tìm thấy bình yên bằng cách lảng tránh cuộc sống.", author: "Virginia Woolf" },
        { text: "Hai ngày quan trọng nhất trong cuộc đời bạn là ngày bạn sinh ra và ngày bạn tìm ra lý do tại sao.", author: "Mark Twain" },
        { text: "Nếu bạn đánh giá một người bằng ngoại hình, bạn không có thời gian để yêu thương họ.", author: "Mẹ Teresa" },
        { text: "Sự thật giống như mặt trời. Bạn có thể che khuất nó trong một thời gian, nhưng nó sẽ không đi đâu cả.", author: "Elvis Presley" },
        { text: "Giận dữ là một cục than hồng mà bạn nắm trong tay với ý định ném vào người khác; nhưng bạn lại là người bị bỏng.", author: "Gautama Buddha" },
        { text: "Sự tôn trọng phải được kiếm được, sự trung thực phải được đánh giá cao, tình yêu phải đạt được, và sự trung thành sẽ được đền đáp.", author: "Khuyết danh" },
        { text: "Hãy làm việc tốt một cách lặng lẽ và để thành công tự tạo tiếng vang.", author: "Frank Ocean" },
        { text: "Sự phong phú không đong đếm bằng những gì chúng ta có, mà bằng những gì chúng ta trân trọng.", author: "Epicurus" },
        { text: "Nỗi đau là tất yếu, nhưng đau khổ là do lựa chọn.", author: "Haruki Murakami" },
        { text: "Sự sống vốn ngắn ngủi, vì vậy đừng làm nó ngắn hơn bằng cách lãng phí thời gian.", author: "Victor Hugo" },
        { text: "Khả năng vĩ đại nhất của con người không phải là thay đổi thế giới, mà là thay đổi chính mình.", author: "Mahatma Gandhi" },
        { text: "Trí tuệ thực sự không phải là không bao giờ phạm sai lầm, mà là khả năng tự tha thứ sau khi đã sửa chữa nó.", author: "Seneca" },
        { text: "Bạn không thể gột rửa bóng tối bằng bóng tối, chỉ có ánh sáng mới làm được điều đó.", author: "Martin Luther King Jr." },
        { text: "Khiêm tốn không phải là nghĩ kém về bản thân, mà là ít nghĩ về bản thân hơn.", author: "C.S. Lewis" },
        { text: "Người hạnh phúc nhất không phải là người sống trong nhung lụa, mà là người có thể nở nụ cười trong giông bão.", author: "Epictetus" },
        { text: "Lạc quan là hạt giống của mọi hy vọng và nỗ lực.", author: "Helen Keller" },
        { text: "Đừng chờ người khác mang lại ánh sáng, hãy tự mình trở thành ánh sáng.", author: "Gautama Buddha" },
        { text: "Tâm hồn không bao giờ có thể tự do nếu không học cách buông bỏ.", author: "Lão Tử" },
        { text: "Cách duy nhất để có một người bạn là trở thành một người bạn.", author: "Ralph Waldo Emerson" },
        { text: "Một ngọn nến không mất đi ánh sáng khi thắp sáng một ngọn nến khác.", author: "Rumi" },
        { text: "Hãy lắng nghe với sự tò mò. Hãy nói với sự trung thực. Hãy hành động với sự chính trực.", author: "Roy T. Bennett" },
        { text: "Sự vĩ đại của con người không nằm ở việc tạo ra tài sản, mà ở khả năng thấu cảm.", author: "Dalai Lama" },
        { text: "Người khôn ngoan không tranh cãi, kẻ tranh cãi không khôn ngoan.", author: "Lão Tử" },
        { text: "Tất cả mọi thứ đều có vẻ đẹp, nhưng không phải ai cũng nhìn thấy.", author: "Khổng Tử" },
        { text: "Điều dũng cảm nhất mà bạn có thể làm là hiểu chính mình.", author: "Carl Jung" },
        { text: "Tự do thực sự là khi bạn không còn cần ai phải công nhận giá trị của mình.", author: "Osho" },
        { text: "Sự tha thứ là mùi hương mà loài hoa violet để lại trên gót chân người đã giẫm nát nó.", author: "Mark Twain" },
        { text: "Biết người là thông minh, biết mình là bậc trí.", author: "Lão Tử" },
        { text: "Trái tim rộng mở giống như bầu trời, không bao giờ bị những đám mây u ám che khuất mãi mãi.", author: "Thích Nhất Hạnh" },
        { text: "Hãy trân trọng ngày hôm nay, vì nó sẽ sớm trở thành ngày hôm qua.", author: "Khuyết danh" },
        { text: "Sự kiêu ngạo tạo ra khoảng cách, sự khiêm tốn tạo ra sự kết nối.", author: "Khuyết danh" },
        { text: "Mỗi người chúng ta đều là kiến trúc sư cho hạnh phúc của riêng mình.", author: "Joseph Murphy" },
        { text: "Người giàu có nhất không phải là người có nhiều nhất, mà là người cần ít nhất.", author: "Epicurus" },
        { text: "Tình yêu thương là sức mạnh duy nhất có khả năng biến kẻ thù thành bạn bè.", author: "Martin Luther King Jr." },
        { text: "Không có con đường dẫn tới bình yên, bình yên là con đường.", author: "A.J. Muste" },
        { text: "Bạn không thể tìm thấy biển mới nếu không có can đảm rời mắt khỏi bờ.", author: "André Gide" },
        { text: "Mọi thứ bạn cần để thành công đã có sẵn trong bạn. Hãy đánh thức nó.", author: "Ralph Waldo Emerson" },
        { text: "Bạn là tác giả của cuộc đời mình. Đừng để người khác viết kịch bản thay bạn.", author: "Khuyết danh" },
        { text: "Những tâm hồn dũng cảm không bao giờ chết, họ chỉ chìm vào giấc ngủ để tiếp tục giấc mơ ở một thế giới khác.", author: "Khuyết danh" },
        { text: "Cuộc sống không phải là tìm lại chính mình. Cuộc sống là tạo ra chính mình.", author: "George Bernard Shaw" },
        { text: "Trưởng thành là khi bạn nhận ra điều gì thực sự quan trọng và bỏ qua những thứ vô nghĩa.", author: "Seneca" },
        { text: "Người thực sự tự do là người có thể mỉm cười trước mọi nghịch cảnh.", author: "Epictetus" },
        { text: "Hãy để tình yêu thương là la bàn dẫn đường cho cuộc sống của bạn.", author: "Rumi" },
        { text: "Điều gì không thể giết chết bạn sẽ làm bạn mạnh mẽ hơn.", author: "Friedrich Nietzsche" }
    ];

    const quoteBox = document.getElementById('daily-quote-box');
    const quoteText = document.getElementById('quote-text');
    const quoteAuthor = document.getElementById('quote-author');

    if (quoteBox && !document.body.classList.contains('has-slide')) {
        const randomQuote = edevxQuotes[Math.floor(Math.random() * edevxQuotes.length)];
        quoteText.textContent = `"${randomQuote.text}"`;
        quoteAuthor.textContent = randomQuote.author;
        
        quoteBox.classList.remove('hidden'); 
        setTimeout(() => { quoteBox.classList.remove('opacity-0'); }, 150); 
    }
});